GET https://localhost

###

POST https://localhost/auth/signup
Content-Type: application/json

{
    "username": "Kanav01",
    "password": "jaimahamai"
}

###

POST https://localhost/auth/login
Content-Type: application/json

{
    "username": "Kanav01",
    "password": "jaimahamai",
    "applicationHash": "123"
}